### PR TITLE
Add skins

### PR DESCRIPTION
**Pull request by b3u**
Resolves issue #25
# Add 3 skin textures
  * Harry Potter
  * Harry Potter (Ravenclaw)
  * Minetest T-shirt

### CODE REVIEW

**Comment by bell07** [comment]
I like the Minetest T-shirt skin, but the both Harry Ptter are not neutral enogh to be default skin. Please no themed skins. Just neutral like Sam, Alex or Steave, to be useable in any subgame. 

The second point: Since skinsdb supports 1.8 format skins I would be glad to see such skins by default in skinsdb, not the "simple" 1.0 format skins.
See http://minecraft.novaskin.me/ for examples and skin editor.

**Comment by b3u** [comment]
sure.

**Comment by bell07** [comment]
Nice!

Can you give the "T-Shirt" a real name? Paul?

Now we need some females ;-)

Do you think we can get the default skins in 1.8-er version?

**Comment by SmallJoker** [comment]
Would you please be so nice and run optipng/pngcrush or oxipng to reduce the image sizes? Server owners and the players who join will be thankful.

**Comment by SmallJoker** [comment]
Remote repository is dead.

**Pull request closed without merging**
