### PR TITLE
add updater script

### PR DESCRIPTION
**Pull request by tsao-chi**
fix https://github.com/minetest-mods/skinsdb/issues/38, https://github.com/minetest-mods/skinsdb/issues/31

### CODE REVIEW

**Comment by tsao-chi** [comment]
ping @bell07

**Comment by bell07** [comment]
I like the script idea. But the script does not work with minetest compiled with RUN_IN_PLACE
The RUN_IN_PLACE is recommended for users compiling the minetest from source.

**Comment by tsao-chi** [comment]
Users can download compiled minetest 5.1.1 somewhere

**Comment by tsao-chi** [comment]
ping @bell07

**Comment by bell07** [comment]
@SmallJoker, should we merge that? Have concerns about the script is not compatible to the RUN_IN_PLACE version

**Comment by SmallJoker** [comment]
This solution looks very hacky - and the execution chain _bash -> Minetest -> skinsdb -> Skin files -> bash_ is very fragile. At least the RUN_IN_PLACE exception should be documented (README.md).
Generally no objections from my side because I would not use this script anyway.

**Comment by SmallJoker** [comment]
Superseded by #48

**Pull request closed without merging**
