### PR TITLE
remove all updater

### PR DESCRIPTION
**Pull request by bell07**
remove all updater to solve CC-BY-NC-SA and Newtonsoft license issues
Fix for #19

### CODE REVIEW

**Comment by SmallJoker** [comment]
Well, there has to be some kind of media fetcher/downloader. Without it it's much harder for server owners to get the skins from the database. What if we require `trusted_mods = skinsdb` to move the updater to a Lua script which can then be executed by the server owner?

**Comment by sofar** [comment]
that's OK, but it doesn't need to run in the game environment, after 
all, you'd have to restart the server to get any new textures.

So, a lua script that downloads standalone would also work. Or even just 
a different shell script that uses e.g. curl.

**Comment by bell07** [comment]
Maybe the author adjust the shell-script license to a compatible one. I like the GPL-3 because this license dissallow usage on sealed hardware.
I opened an issue in project I forked from: https://github.com/FozLand/u_skins/issues/3, but I see now the origin is https://github.com/SmallJoker/minetest-u_skinsdb
@SmallJoker are you the shell-script owner? Can you adjust the license?

Other way is: The shell script is not really depends on skinsdb or on minetest and can be published with own license in own project, with usefull default TEXTUREDEST and METADEST set.

Unsure if other updater was ever used because of does not work.

Lua updater will be nice, but the issue is the fetches skins are available only after game restart. "trusted_mods" is not necessary if the updater mod saves the files in his textures/metadata folder and just register them in skinsdb.

I search for updaters on other ressources with 1.8er skins instead, like https://www.minecraftskins.com/ or http://minecraft.novaskin.me/gallery

**Comment by SmallJoker** [comment]
@bell07 As written in the README, it's Fritigern who wrote the shell script: https://forum.minetest.net/viewtopic.php?p=158183#p158183 - I think they've sent me the script in a PM.

skinsdb does not require, load or embed any of the non-GPL-compatible works; and GPL only applies to the source code. However, I'm not sure whether or how these licenses may be mixed (or not).

@sofar Standalone Lua scripts cannot download files, which would lead to using curl or wget to fetch the list and download the files. I think that would be done best in shell.

**Pull request merged**
