### PR TITLE
fixed first person arm rotation

### PR DESCRIPTION
**Pull request by BlockAndPixelAge**
As mentioned by @Lemente that someone needs to do the pull request.

https://github.com/minetest-mods/skinsdb/issues/99#issuecomment-2226860384

Here a pull request, with the first person arm fix, while the arm for 1.8 having a 3d layer, done by Lemente.

This is my first pull request that I ever did, so the only thing I don't know how to do is, how to edit the readme to add Lemente to the credits for the updated 1.8 hand.

Hope that I don't count as a contributor.

### CODE REVIEW

**Review by SmallJoker — COMMENTED** [review]
Tested skin: jojoa1997 (character 24 from the database)

comparison

Looks good.

1. Why is `skinsdb_hand_18.b3d` 200 times larger than the previous version? It seems to be that there's quite some unused data included. This might seem like a nitpick, but consider that servers need to distribute this file to every new client.
2. Please change the commit author to Lemente (git commit --amend). See tutorials.

**Comment by BlockAndPixelAge** [comment]
@SmallJoker 

Ehhhh, where do I find the correct tutorial, if I try to search for something it's not really what I'm looking for?

Do I need to do something by commit here in the pull request,that is beside the conversation tab?

**Comment by BlockAndPixelAge** [comment]
@SmallJoker 

Sorry to say this but, I don't understand the tutorials I find. >A<

**Comment by BlockAndPixelAge** [comment]
@SmallJoker 

I'm too incompetent for the commit author change. Don't understand tutorials in text or video format.
If I transfer ownership of the repository, would that close the pull request or would it stay open?

**Comment by BlockAndPixelAge** [comment]
I'm too stupid to understand the tutorials.

Definitely not amateur friendly, which I am.

**Comment by BlockAndPixelAge** [comment]
@SmallJoker 

I give up, I don't understand the tutorials for changing the commit author.

Guess I will close the pull request and wait that someone who knows how to do it, will do the pull request.

**Comment by Lemente** [comment]
>     1. Why is `skinsdb_hand_18.b3d` 200 times larger than the previous version?
The outer skin layer has been made 3D, which means that eache pixel is now a 3D cube.
So the 3D model went from 24 tris to 2700 tri.

**Comment by SmallJoker** [comment]
@BlockAndPixelAge

```sh
# modify the commit
git commit --amend --author="Linus Torvalds <linus@torvalds.com>"

# overwrite your branch to use the new commit
git push --force
```

---

@Lemente

Thank you for clarifying. That does explain the size difference. However, I am yet not sure why this is needed. Unfortunately, precision issues might cause visual artifacts like reported here: https://github.com/minetest/minetest/issues/4912 . Hence, if it would be possible to use fewer adjacent polygons, this could largely be avoided on such affected hardware. That aside, it might also perform slightly better on ancient hardware (but that's not my concern).

**Comment by BlockAndPixelAge** [comment]
@SmallJoker 

I don't see how to do it here directly in Github, and from what I roughly somehow but not really understand from Tutorials, is, that I somehow need to have Github Desktop (yay, downloading extra software -.-) and that it's somehow possible to do that even after a pull request.

And I use the free option of Github

**Comment by BlockAndPixelAge** [comment]
Comment written on smartphone.

@SmallJoker 
@Lemente 

Bad news and bad news.
1. I am still not able to understand it
2.  and my pc broke, was an old on and Minecraft wouldn't run on it, and when I get a new one I don't know, go still to school, and my parents think it broke because of what I was trying to do (commit author change).

So there are for now only 2-3 options.
1. Transfer the ownership to one of the maintainer.
2. Doing the pull request now and if it's possible on your site, to change the commit author after the pull request
3. Someone else is doing the pull request.

At the moment you can't count on me, because of what happened to my pc. >A<

**Comment by BlockAndPixelAge** [comment]
Comment written on smartphone.

@SmallJoker
@Lemente

Bad news and bad news.

1. I am still not able to understand the stuff with commit author change.
2. and my pc broke, was an old on and Minecraft wouldn't run on it, and when I get a new one I don't know, go still to school, and my parents think it broke because of what I was trying to do (commit author change).

So there are for now only 2-3 options.

1. Transfer the ownership to one of the maintainer.
2. Doing the pull request now and if it's possible on your site, to change the commit author after the pull request
3. Someone else is doing the pull request.

At the moment you can't count on me, because of what happened to my pc. >A<

**Comment by BlockAndPixelAge** [comment]
@SmallJoker 
I close the pull request, because no PC, and not understanding the tutorials at all. Someone who knows how to change the commit author, should do it.

Sorry.

**Comment by BlockAndPixelAge** [comment]
.

**Comment by BlockAndPixelAge** [comment]
@SmallJoker 
@Lemente

**Comment by BlockAndPixelAge** [comment]
@SmallJoker 

Reopen it, but I'm completely unable to do this commit author ---amend thingie.

Just want to say, learning capacitys are different from people to people, some can learn specific things fast, other more slowly, and than there are some people that can't learn the specific things, no matter how much effort they are putting into it.

Even now I absolutely don't understand this, and did I mention that I still don't have a PC.

If it's possible to change the commit author after the pull request, please do it.

**Comment by BlockAndPixelAge** [comment]
@bell07 @SmallJoker

Can someone take this over, and know how to do the author change, or is there no interest that this Issue get finally fixed?
I mentioned few times, that I don't understand this "commit author amend", so that the Author get changed to @Lemente ,
and 3 months already passed, since the pull request is open. (if we don't count the closing of the PR)

Or the pull request will be done as is, and hope that I won't be listed as contributor, when I delete the Account.

**Comment by BlockAndPixelAge** [comment]
@bell07 @SmallJoker

Can someone, who knows how to do the author change, take over, or is there no interest that this Issue get finally fixed?
I mentioned few times, that I don't understand this "commit author amend", so that the Author get changed to @Lemente ,
and 3 months already passed, since the pull request is open. (if we don't count the closing of the PR)

Or the pull request will be done as is, and hope that I won't be listed as contributor, when I delete the Account.

**Comment by BlockAndPixelAge** [comment]
@bell07 @SmallJoker

Can someone, who knows how to do the author change, take over, or is there no interest that this Issue get finally fixed?
I mentioned few times, that I don't understand this "commit author amend", so that the Author get changed to @Lemente ,
and 3 months already passed, since the pull request is open. (if we don't count the closing of the PR)

Or the pull request will be done as is, and hope that I won't be listed as contributor, when I delete the Account.

**Comment by bell07** [comment]
@BlockAndPixelAge , I do not have experience about commit author ---amend too. 
For my point of view  the easiest way is @Lemente fork the repository https://github.com/BlockAndPixelAge/skinsdb. Do addition changes in his fork and create new Pull request with all changes.

**Comment by BlockAndPixelAge** [comment]
@Bell07

Well, I forked this Master here, downloaded @Lemente fork for the fix of the first person arm, and opened the pull request.
Lementes fork having actually all files ready, but a custom 3d character model with 3d layer too, but it don't work with 3d Armor, and shouldn't replace the 3d Model from this mod. I guess making a branch without the 3d character model would be enough, not necessary to create a second fork.

Otherwise I guess @SmallJoker could maybe do it too, as someone who is even developing on Minetest, now Luanti, I guess should have enough knowledge for it. I mean they wrote that I could change the author, so I guess they know how to do the commit author ---amend too, right?

Fanfact, this is actually my second pull request I opened, the first was with the fork I did itself.

Otherwise after the next comment in general, I close the pull request, again.
Want to finally delete my Account, that I actually made only for this Issue. ;)

**Comment by BlockAndPixelAge** [comment]
@bell07

Well, I forked this Master here, downloaded @Lemente fork for the fix of the first person arm, and opened the pull request.
Lementes fork having actually all files ready, but a custom 3d character model with 3d layer too, but it don't work with 3d Armor, and shouldn't replace the 3d Model from this mod. I guess making a branch without the 3d character model would be enough, not necessary to create a second fork.

Otherwise I guess @SmallJoker could maybe do it too, as someone who is even developing on Minetest, now Luanti, I guess should have enough knowledge for it. I mean they wrote that I could change the author, so I guess they know how to do the commit author ---amend too, right?

Or take the fixed hand files from @Lemente fork, and upload them directly, with the description "fixed by Lemente".

Fanfact, this is actually my second pull request I opened, the first was with the fork I did itself.

Otherwise after the next comment in general, I close the pull request, again.
Want to finally delete my Account, that I actually made only for this Issue. ;)

**Comment by BlockAndPixelAge** [comment]
@bell07

Well, I forked this Master here, downloaded @Lemente fork for the fix of the first person arm, and opened the pull request.
Lementes fork having actually all files ready, but a custom 3d character model with 3d layer too, but it don't work with 3d Armor, and shouldn't replace the 3d Model from this mod. I guess making a branch without the 3d character model would be enough, not necessary to create a second fork.

Otherwise I guess @SmallJoker could maybe do it too, as someone who is even developing on Minetest, now Luanti, I guess should have enough knowledge for it. I mean they wrote that I could change the author, so I guess they know how to do the commit author ---amend too, right?

Or take the fixed hand files from @Lemente fork, and upload them directly, with the description "fixed by Lemente".

Otherwise I will close the pull request now.

**Pull request closed without merging**
